/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
import flash.display.Sprite;

import test.DecisionTreeAdditionTest;
import test.DecisionTreePathfindingTest;

public class FlexUnitCompilerApplication extends Sprite
{
	private var DescisionTree_DescisionTreePathfindingTest_obj:test.DecisionTreePathfindingTest;
	private var DescisionTree_DescisionTreeTest_obj:test.DecisionTreeAdditionTest;	
}
}